### ISSUE TITLE
How quick does it revoke tokens?

### ISSUE THREAD

**Issue by JDOG787** [CoolCoderSJ/TokenRevoker#1]
Would there be time for someone to steal the token and use it before its revoked?

**Comment by ch1ck3n-byte** [comment]
of course

**Comment by CoolCoderSJ** [comment]
@ch1ck3n-byte There would not be enough time. I did a time check- Discord revokes your token almost instantly, take a look

![screen-recording](https://user-images.githubusercontent.com/53063247/118064852-d6b42400-b369-11eb-9f68-149cecbd190b.gif)
